### ISSUE TITLE
Conflicting global and specific delegations

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#24]
Offshoot of #9:

If a global delegation is given to a delegate, but then another one is given specifically for a proposal by the same delegator to a third person, the former should still work for any other proposal.

**Comment by jinjagit** [comment]
And also in the opposite order. If proposal specific delegation created, then if delegator subsequently creates a global delegation, only the proposal specific delegation is counted for that proposal result (and otherwsie the global delegation continues).
This may be best resolved when calculating voting results.

**Comment by jinjagit** [comment]
Manual testing reveals that global and proposal-specific delegations correctly weight the votes of delegates when the delegations are created before the related votes, but not when votes are created before the related delegations. The issue of delegation creation not updating voting weights/results correctly is addressed in issue #52.  
  
I have attempted to create 2 absinthe tests in PR #XXX [update when PR created/merged] that test each of the above scenarios, with the latter being skipped for now, as is failing due to reason described above.

**Comment by jinjagit** [comment]
Covered in #144
