### ISSUE TITLE
Expose Participant :uuid field on API

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/api#67]
Add to graphql schema and resolvers

**Comment by jinjagit** [comment]
So, we managed to get the field uuid exposed in GraphQL quite easily, in that it could be returned in a query like so:
`query { Participant(id: 2) { uuid}}`
Is that all this issue requires?
We went further and made it so that GraphQL uses uuid as it's root query for Partcipant, but I think this may be moving into the following issue (set uuid to 'primary field), and this approach still needs work on integration with the other API actions on Participant.

**Comment by jinjagit** [comment]
i.e. I'm not sure we can 'add to resolvers' without setting uuid to the root GraphQL query for participant (since GraphQL will complain if we find participant by uuid, without it being the root query, though it will do it). This then breaks voting, fails test: Voting: test votes get_vote!/3, so would mean moving into working on Votes? (not just Participant)

**Comment by niklaslong** [comment]
I'd do it in the following steps:

- add `uuid` field in schema  + custom type for `uuid` for all resources
- replace `id` with `uuid` as primary key + fix tests for all resources

These two could also be broken into several PRs but it might be annoying to handle the relationships if half the resources are using `id` and the other half are using `uuid`...

@oliverbarnes thoughts?

**Comment by oliverbarnes** [comment]
@jinjagit I see what you mean, and @niklaslong I think your suggestion makes sense. A single PR for the former, then another for the latter

**Comment by jinjagit** [comment]
closed, as moved to [#76](https://github.com/liquidvotingio/api/pull/76), following GithHub weirdness.
